### PR TITLE
Add a separate build of the dynamic library for OSX on M1 chip.

### PR DESCRIPTION
**Pull request by svetlyak40wt**

### CODE REVIEW

**Comment by Shinmera** [comment]
The M1 is an ARM64 chip, right? So shouldn't the feature check be #+ARM64 and the file be called arm64?

**Comment by svetlyak40wt** [comment]
Good catch. I was in hurry this morning :(

Fixed!

**Comment by Shinmera** [comment]
Please keep the naming of the amd64 file consistent, as well.

**Comment by svetlyak40wt** [comment]
Done.

**Comment by Shinmera** [comment]
Thank you!

**Pull request merged**
