### PR TITLE
Apple arm64 build

### PR DESCRIPTION
**Pull request by egao1980**
Built on M2 chip.

I had to modify the Makefile so please check.

```
CL-USER> (defpackage :mypackage
  (:use :cl)
  (:local-nicknames (:vorbis :org.shirakumo.fraf.vorbis)))
#<PACKAGE "MYPACKAGE">
CL-USER> (in-package :mypackage)
#<PACKAGE "MYPACKAGE">
MYPACKAGE> (vorbis:with-file (file #p"~/Downloads/Example.ogg")
  (values (vorbis:channels file)
          (vorbis:samplerate file)
          (vorbis:decode-frame file)))
2 (2 bits, #x2, #o2, #b10)
44100 (16 bits, #xAC44)
(#(-0.0016679106 -0.0014190403 -6.335551e-4 -3.0373447e-4 -5.0332217e-4
   -0.0012545632 -0.0019440461 -0.0022326277 -0.0021361285 -0.0011725959
   -3.930586e-4 -1.6912533e-4 -1.3606659e-4 -4.1955686e-4 -7.429542e-4
   -0.0011247447 -0.0011597393 -0.0012164166 -0.0012654146 -8.1003236e-4
   -0.0010466797 -0.001447995 -0.0015532384 -0.0018069217 -0.0014518641
   -8.8493776e-4 -4.2401988e-4 1.09118526e-4 4.2774287e-4 5.823577e-4
   0.0011815315 0.0021144405 0.0028377401 0.0038310215 0.0042978404 0.003971275
   0.0033023006 0.0019197876 5.970135e-4 -7.72275e-4 -0.002008797 -0.0026109093
   -0.002531766 -0.0015676257 -0.0012761443 -0.0018012032 -0.002083239
   -0.0019266512 -0.0010249135 2.479589e-4 0.0013004215 0.0015564417
   7.553871e-4 -6.082277e-4 -0.0017639814 -0.0019408831 -0.0014007649
   -0.0016313351 -0.0023114039 -0.0029552355 -0.0039757714 -0.0037271613
   -0.00284682 -0.002282705 -0.0013574306 -4.949921e-4 8.138552e-4 0.0015486265
   0.0014093269 0.0010441683 2.6018824e-7 -5.2772777e-4 6.3372165e-4
   0.0026022082 0.0032840986 0.003268696 0.0025721393 0.0010290516 3.515552e-5
   -0.001074559 -0.0013632919 -0.0013108205 -9.536411e-4 1.0774407e-4
```

### CODE REVIEW

**Comment by Shinmera** [comment]
Hmm, avx2 is also an x86 instruction set, maybe try `-mfpu=neon` instead of `-mavx2 -march=native`? I'm not sure about the exact best compiler flags to use, though.

**Comment by egao1980** [comment]
As far as I understand the `-mfpu` will be autodetected, and I think `native` just forces M1/2/3 in case user has Rosetta installed.

**Comment by egao1980** [comment]
Need M1 to verify.

**Comment by Shinmera** [comment]
Yeah that's why I usually avoid `-march=native` since it can over-specialise. I'll merge this for now, but if you know someone with an M1 that can test I'd be most grateful!

**Pull request merged**
